add hw1CLI
Hotckiss/SoftwareDesign pull request #1
Opened 2019-02-05 14:19 UTC by Hotckiss

2019-02-16 02:27 UTC, ArtyomLobanov requested changes

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/build.gradle
> +
Собирающийся jar-файл нельзя запустить т.к. не указана точка входа в программу.

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/Main.java
> +    private static Logger logger = Logger.getLogger(Main.class.getName());
Хочется логгировать - логгируйте куда-нибудь в отдельный файл. Зачем вы всё это пользователю вываливаете?

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/Main.java
> +        Parser parser = new ParserImpl();
Обязательно каждый раз с нуля создавать? И боюсь представить, как вы текущее состояние интерпретатора храните.

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/CatCommand.java
> +     * File name is the last argument, all other arguments are ignored
Может тогда всё-таки ошибку вывести? О неожиданном поведении лучше сразу сообщать. Мб пользователь кавычки забыл, например.

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/CatCommand.java
> +            return CommandResult.ABORT;
А пользователю никаких подробностей не сообщим? (Ну кроме логов, которые пользователь в нормальном состоянии видеть не должен)

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/EchoCommand.java
> +        return new CommandResult(new ArrayList<>(arguments));
Получается, echo каждый аргумент на новой строке печатает? Не канон. Могли бы хоть упомянуть где-нибудь.

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(lines.size())).toString());
Тут можно было использовать Integer.toString(lines.size())

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
В процессе разбиения файла на строки и последующего склеивания их обратно поломались окончания строк (а они бывают разные \r, \n, \r\n). Из-за этого размер файла считается неправильно. Вообще стоит использовать готовые реализации. Например, [File.length()](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#length--)

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/interpreter/parser/ParserImpl.java
> +            if (queue.element().equals(' ') || queue.element().equals('\n')) {
'\r'?

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/interpreter/tokenizer/TokenizerImpl.java
> +    public static final Set<Character> WORD_BREAK_CHARACTERS = new HashSet<>();
`public static final Set<Character> WORD_BREAK_CHARACTERS = new HashSet<>(Arrays.asList(' ', '"', '\n', '\''));`

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/interpreter/tokenizer/TokenizerImpl.java
> +    public static final Set<Character> NAME_CHARACTERS = new HashSet<>();
Вообще можно было же их сразу Предикатами объявлять.
Как-нибудь так, скажем
```
public static final Predicate<Character> p = x -> Character.isLetterOrDigit(x) || "-:_".indexOf(x) != -1;
```

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/utils/Environment.java
> +    private static final Logger logger = Logger.getLogger(Environment.class.getName());
Во-первых, определитесь в каком порядке вы модификаторы пишите.
Во-вторых, давайте хотя бы Singleton из этого сделаем. А то сейчас это вообще что-то странное.

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/utils/FileIO.java
> +                        writer.write(str + "\n");
[System.lineSeparator()](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--)

2019-02-16 02:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/utils/FileIO.java
> +                        writer.flush();
А зачем flush после каждого вывода? Можно один в конце.

2019-02-18 11:45 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
можно взять avaliable у стрима и уже норм

2019-02-18 11:50 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
>Returns an estimate of the number of remaining bytes that can be read (or skipped over) from this input stream **without blocking** by the next invocation of a method for this input stream

Из документации к [FileInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/FileInputStream.html#available--). Для больших файлов работать не будет.

2019-02-18 11:50 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
>Returns an estimate of the number of remaining bytes that can be read (or skipped over) from this input stream **without blocking** by the next invocation of a method for this input stream

Из документации к [FileInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/FileInputStream.html#available--). Для больших файлов работать не будет.

2019-02-18 11:52 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
мне просто не нравится что для создания file надо передавать path, и видимо это должен быть всегда absolute path, либо всегда его делать относительным приписыванием префикса

2019-02-18 11:57 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
А угадайте, что FileInputStream делает
```
    public FileInputStream(String name) throws FileNotFoundException {
        this(name != null ? new File(name) : null);
    }
```

2019-02-18 11:59 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/WcCommand.java
> +        result.add((Integer.valueOf(joinedLinesString.getBytes().length)).toString());
окееей

2019-02-20 12:31 UTC, ArtyomLobanov requested changes

2019-02-20 12:31 UTC, ArtyomLobanov commented on hw1CLI/src/test/java/kirilenko/cli/commands/implementation/ExternalCommandTest.java
> +                .execute(Collections.emptyList()).getOutput();
Этот тест падает. Если хочется, чтобы работали консольные команды под windows, надо запускать не
`Runtime.getRuntime().exec(new String[]{"echo", "text"})`
а вот так
`Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c", "echo", "text"})`

2019-02-20 12:31 UTC, ArtyomLobanov commented on hw1CLI/build.gradle
> +mainClassName = 'kirilenko.cli.Main'
Всё ещё нет. [Попробуйте](https://stackoverflow.com/questions/21721119/creating-runnable-jar-with-gradle) ещё раз.

2019-02-20 12:31 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/utils/Environment.java
> +public final class Environment {
А тут ничего не поменялось :( 
Вот у вас на схеме есть некий класс CLI, которого что-то нигде не видно. Вот давайте его всё-таки создадим и будем хранить информацию о переменных в конкретном экземпляре.

2019-02-20 12:31 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/GrepCommand.java
> +public class GrepCommand extends AbstractCommand {
А это вообще не из этого задания

2019-02-20 12:44 UTC, Hotckiss commented on hw1CLI/build.gradle
> +mainClassName = 'kirilenko.cli.Main'
именно поэтому я еще не заливал в hwproj что исправлено все, я пока не проверял этот момент как раз

2019-02-20 12:46 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/utils/Environment.java
> +public final class Environment {
CLI это Main, не понимаю в чем смысл таскать везде инстанс окружения в одной консоли

2019-02-20 12:49 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/utils/Environment.java
> +public final class Environment {
Мы же хотим поддерживаемую и расширяемую архитектуру. Сегодня она одна, завтра понадобятся функции или подпроцессы.

2019-02-20 12:49 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/utils/Environment.java
> +public final class Environment {
если есть действительно разумеые команды которые внутри себя могу делать локальные присваивания, то в этом есть смысл

2019-02-20 12:52 UTC, ArtyomLobanov commented on hw1CLI/build.gradle
> +mainClassName = 'kirilenko.cli.Main'
Действительно. Тут мой косяк)

2019-03-26 20:24 UTC, Hotckiss commented on hw1CLI/src/test/java/kirilenko/cli/commands/implementation/ExternalCommandTest.java
> +                .execute(Collections.emptyList()).getOutput();
Сяду за комп с виндой исправлять)

2019-03-26 20:37 UTC, Hotckiss commented on hw1CLI/src/test/java/kirilenko/cli/commands/implementation/ExternalCommandTest.java
> +                .execute(Collections.emptyList()).getOutput();
Сделал if на SystemUtils.IS_OS_WINDOWS, для остальных осей оставил как было, хотя конечно такого рода тесты не кроссплатформенные и в системе XXX развалятся, но тогда этот тест вообще выкинуть надо

2019-03-26 21:21 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/utils/Environment.java
> +public final class Environment {
ок, сделал окружение локальным инстансом, который создается в CLI или в соответствующем тестовом классе, командам он теперь также передается. и если окружение нужно им теоретически, оно у них есть

2019-03-26 21:22 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/GrepCommand.java
> +public class GrepCommand extends AbstractCommand {
убрал, вообще в идеале надо сначала добить это дз до аппрува, а уже после этого подтянуть ветку актуальную во 2 дз

2019-03-26 21:22 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/GrepCommand.java
> +public class GrepCommand extends AbstractCommand {
но я наверное все равно перетяну уже сейчас, думаю что осталось добить немного

2019-03-26 21:23 UTC, Hotckiss commented on hw1CLI/build.gradle
> +mainClassName = 'kirilenko.cli.Main'
должен был справиться

2019-03-26 21:24 UTC, Hotckiss commented
@ArtyomLobanov подправил остатки, на винде работает

2019-03-27 18:04 UTC, ArtyomLobanov commented
Зависимости не упаковываются.
```cmd
C:\practice\kirilenko\SoftwareDesign\hw1CLI>java -jar build\libs\hw1CLI-1.0-SNAPSHOT.jar
echo text
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Lists
        at kirilenko.cli.interpreter.parser.ParserImpl.buildTree(ParserImpl.java:105)
        at kirilenko.cli.interpreter.parser.ParserImpl.parse(ParserImpl.java:96)
        at kirilenko.cli.Main.execute(Main.java:53)
        at kirilenko.cli.Main.main(Main.java:33)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 4 more
```

2019-03-27 18:06 UTC, Hotckiss commented
ок сейчас сам потыкаю jar

2019-03-27 18:10 UTC, ArtyomLobanov commented
Гуглите jar with dependencies

2019-03-27 18:13 UTC, Hotckiss commented
сейчас сам все равно еще попробую собрать

2019-03-27 18:23 UTC, Hotckiss commented
@ArtyomLobanov у меня заработало

2019-03-27 18:27 UTC, ArtyomLobanov commented
У меня тоже. @yurii-litvinov

2019-03-27 19:04 UTC, yurii-litvinov approved these changes
Ввожу заведомо несуществующую команду, ничего не происходит. Хочется сообщения об ошибке.

Но поскольку больше серьёзных проблем не обнаружено, зачтена

2019-03-27 19:04 UTC, yurii-litvinov commented on hw1CLI/src/main/java/kirilenko/cli/CLILogger.java
> +package kirilenko.cli;
Имена пакетов несколько неканоничны, должнгы начинаться с доменного имени наоборот

2019-03-27 19:04 UTC, yurii-litvinov commented on hw1CLI/src/main/java/kirilenko/cli/commands/CommandResult.java
> +    public static final CommandResult EXIT = new CommandResult(false, true, Collections.emptyList());
Возможно, это можно былосделать настоящим enum-ом, благо в Java они полноценные классы с конструкторами для каждого элемента

2019-03-27 19:16 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/CLILogger.java
> +package kirilenko.cli;
там с какого-то момента все логи уехали в отдельный файл, поэтому в stderr и не пишет никаких ошибок

2019-03-27 19:16 UTC, Hotckiss commented on hw1CLI/src/main/java/kirilenko/cli/CLILogger.java
> +package kirilenko.cli;
хотя в логе тоже не пишется, что команды нет, оно пишет, что попытался вызвать внешнюю команду с таким названием но не получилось ее выполнить

2019-04-15 13:30 UTC, merged