Docker HW
Hotckiss/SoftwareDesign pull request #10
Opened 2019-06-05 21:47 UTC by Hotckiss

Кириленко, Ерохина

2019-06-05 21:51 UTC, Hotckiss commented
<img width="1440" alt="Снимок экрана 2019-06-06 в 0 46 02" src="https://user-images.githubusercontent.com/22048102/58993077-2b9da600-87f5-11e9-8caf-0ece42d83507.png">
Работает

2019-06-10 19:00 UTC, TanVD requested changes

2019-06-10 19:00 UTC, TanVD commented on composetest5/docker-compose.yml
> +    image: localstack/localstack:0.9.0
Why not 0.9.4?)

2019-06-10 19:00 UTC, TanVD commented on composetest5/init.py
> +        time.sleep(1)
Does not look like a solid solution :)

2019-06-10 19:04 UTC, Hotckiss commented on composetest5/docker-compose.yml
> +    image: localstack/localstack:0.9.0
у меня зависало после скачивания локалстека в докере, где-то прочитал, что в 0.9.4 могут быть проблемы; но вроде как ошибка была в другом и можно вернуть

2019-06-10 19:16 UTC, Hotckiss commented on composetest5/init.py
> +        time.sleep(1)
@TanVD не смотрел подробно, но кажется тут такая же идея, или надо подробнее смотреть?
<img width="1440" alt="Снимок экрана 2019-06-10 в 22 15 39" src="https://user-images.githubusercontent.com/22048102/59220335-60cb3f00-8bcd-11e9-8cf7-c7b8c91a82ef.png">

2019-06-10 19:23 UTC, Hotckiss commented on composetest5/init.py
> +        time.sleep(1)
или нужно поставить какой-то доп таймаут, если все реальтно плохо, и чтобы вечно не крутиться?

2019-06-12 09:25 UTC, TanVD commented on composetest5/docker-compose.yml
> +    image: localstack/localstack:0.9.0
Да, давайте

2019-06-12 09:26 UTC, TanVD commented on composetest5/init.py
> +        time.sleep(1)
Давайте доп таймаут и в начале некоторое время ожидания, чтобы ошибками не засыпало. Есть нормальное решение с опросом сервисного порта  LocalStack, но его я не требую

2019-06-18 11:36 UTC, Hotckiss commented
@TanVD исправил,тут добавил таймаут
А тут еще добавил ограничение на количество итераций цикла, как вариант
https://github.com/Hotckiss/SoftwareDesign/pull/12

2019-06-21 17:29 UTC, Hotckiss commented
Зачли, моржую

2019-06-21 17:29 UTC, merged