Roguelike final
Hotckiss/SoftwareDesign pull request #11
Opened 2019-06-09 11:01 UTC by Hotckiss

@ArtyomLobanov давайте смотреть все сразу вот в этой ветке
Сюда же докинул проверку связности и еще все оставшиеся фиксы по всем веткам

2019-06-10 16:13 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/generators/GenerationUtils.java
> +                        true,
Вот сюда бы конечно строителя пихнуть

2019-06-16 11:21 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/generators/GenerationUtils.java
> +                        true,
upd: добавил

2019-06-17 04:51 UTC, ArtyomLobanov reviewed
1. Предусмотрите возможность заканчивать игру. Если просто закрыть окно, то процессы остаются висеть
![image](https://user-images.githubusercontent.com/9067686/59578771-7ca17a00-90d2-11e9-8242-2ddc1911bc74.png)
2. Добавьте тесты на оглушение
3. Функциональность загрузки игры в процессе игры работает странно - просит ввести имя файла, а я его не знаю т.к. я его не задавал при сохранении. Можно вообще эту функцию убрать.
4. Сохранения должны удаляться при смерти персонажа

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/gameloading/GameSaverAndLoader.java
> +        } finally {
Есть же try-with-resources для таких случаев
```java
        try (FileWriter fr = new FileWriter(file, true);
             BufferedWriter br = new BufferedWriter(fr);
             PrintWriter pw = new PrintWriter(br)) {
            pw.print(text);
        } catch (IOException e) {
            e.printStackTrace();
        }
```

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/gameloading/GameSaverAndLoader.java
> +    public GameModel loadGame() {
Почему не использовали готовые подходы к сериализации? JSON, Protobuf, стандартная java-сериализация?

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
А какой смысл в паттерне команда, если команды создаются и исполняются в одном и том же классе? Смысл появится, если, например, команды будут создаваться в Controller-е и передаваться модели для выполнения.

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +    public void makeMove(@NotNull UserInputProvider provider) throws IOException {
Интерпретацией пользовательского ввода занимается контролер, а не модель. Пусть лучше принимает сразу PlayerMove, а это логику чтения можно убрать в контроллер или в команду Move

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/movable/Player.java
> +            case 'e':
И вот это тоже куда-нибудь в контроллер надо.

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/AggressiveStrategy.java
> +        return defaultStrategy.preferredMove(position, model);
Какие-то совсем слепые противники выходят. Давайте они будут замечать игрока хотя бы, скажем, с 5 клеток.

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/CowardStrategy.java
> +        return availableMoves.get(random.nextInt(availableMoves.size()));
Трусливый моб не просто не нападает на игрока, он убегает прочь от него. У него есть цель в жизни - держаться от игрока подальше, а у вас он по сути случайно гуляет

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/strategies/AbstractStrategy.java
> +    public abstract Move preferredMove(Position position, GameModel model);
На случай более интеллектуальных стратегий, стоило бы передавать не позицию, а самого моба. Вдруг стратегии будут учитывать здоровье моба, его силу?

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/Artifact.java
> +        this.position = position;
А какой смысл несёт это поле, когда артефакт уже подобран игроком? Оно возвращает позицию игрока? Или null? Может стоит разделить сущности "лежащий на земле предмет" и "артефакт, который игрок может хранить в инвентаре и использовать"

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/movable/Player.java
> +                }
Давайте для дз про инвентарь сделаем более гибкую систему экипирования артефактов - предусмотрим возможность работать не только с первым артефактом. И можно как-то показывать игроку, что артефакт надет?

2019-06-17 04:51 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/base/AbstractGameParticipant.java
> +        opponent.health = (int) (Math.max(0, opponent.health - physicalDamage * physicalDamageMultiplier * (1 + Math.abs(getLevel() - 1) * 0.5)));
Следите за длиной строк

2019-06-17 04:53 UTC, Hotckiss commented
@ArtyomLobanov  3– это была функция загрузки карты из файла, в том смысле что не рандомная ненерация, а из файлика

2019-06-17 04:57 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/CowardStrategy.java
> +        return availableMoves.get(random.nextInt(availableMoves.size()));
Его и так поймать тяжело, при равных скоростях его надо загнать в кгол

2019-06-17 05:01 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/gameloading/GameSaverAndLoader.java
> +    public GameModel loadGame() {
хм, делал не я, но кажется что такое интуитивно хочется написать в лоб, так как сложность небольшая
А без намека на json  про него я бы и не вспомнил

2019-06-17 05:02 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Точно не помню, но кажется у команд разные получатели наверное

2019-06-17 05:02 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Есть команды, которые генерят модель, а не обрабатываются ей

2019-06-17 05:04 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/AggressiveStrategy.java
> +        return defaultStrategy.preferredMove(position, model);
Ну тут было расплывчатое понятие)

2019-06-17 05:05 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/Artifact.java
> +        this.position = position;
Наверное там внутри была для этого обертка ArtifactItem

2019-06-17 05:05 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/Artifact.java
> +        this.position = position;
Тогда это легко подправить

2019-06-17 05:06 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Ок, отправляйте кому нужно. Посыл был в том, что исполнять при команды создании в том же месте, где их создали, абсолютно бессмысленно.

2019-06-17 05:06 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/movable/Player.java
> +                }
Не хочу поддерживать N кнопок для N артефактов, тогда сделаю очередь для артефактов размера 5 например, и кнопки 1,2,3,4,5

2019-06-17 05:57 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/AggressiveStrategy.java
> +        return defaultStrategy.preferredMove(position, model);
Мне не нравится план — суть в принципе не в умении писать бфс, а вот в сетевой эти мобы будут очень странно циркулировать между 5 игроками например

2019-06-17 06:03 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/AggressiveStrategy.java
> +        return defaultStrategy.preferredMove(position, model);
Могу сделать для 1 игрока умный ход, а если их много, то как-то не понятно становится

2019-06-17 07:15 UTC, Hotckiss commented
1 - ок
2 - ок
3 - ?, это не загрузка игры, а генерация новой из файла
4 - ок

2019-06-17 08:51 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/movable/Player.java
> +            case 'e':
вынес в команду для хода, из модели автоматически это ушло, так как через нее просто прорастал инпут

2019-06-17 08:54 UTC, Hotckiss commented
осталось еще Х замечаний

2019-06-17 13:15 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/strategies/implementations/AggressiveStrategy.java
> +        return defaultStrategy.preferredMove(position, model);
ок, будут к ближайшему лезть, если их много, радиус видимости 5

2019-06-17 13:57 UTC, Hotckiss commented
осталось поправить артефакты и паттерн команда

2019-06-17 20:04 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/movable/Player.java
> +                }
сделал так: нажимаем цифру от 1 до 9, нажатие соответственно активирует артефакт, либо наоборот. Если артефакт ушел дальше 9, то он утрачен для игрока
В игре помечены плюсиком экипированные, минусом наоборот

2019-06-17 20:05 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/gameloading/GameSaverAndLoader.java
> +    public GameModel loadGame() {
А еще это легче проверять)

2019-06-17 20:11 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/Artifact.java
> +        this.position = position;
на самом деле мне кажется и нет проблемы -- вот этот класс это и есть артефакт на земле, а игрок работает с оберткой ArtifactInInventory. Для удобства он просто хранит в себе артефакт, чтобы не дублировать свойства

2019-06-17 20:13 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/Artifact.java
> +        this.position = position;
разве что переносить все свойства внутрь обертки, но придется очень много всего перелопатить ради сомнительной выгоды

2019-06-17 20:13 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/Artifact.java
> +        this.position = position;
потому что сейчас артефакты по сети летают уже

2019-06-17 20:33 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Короче я все понял

2019-06-17 20:35 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Я так понимаю суть паттерна такая -- есть отправитель, например какой-нибудь MenuItem, есть собственно Command и есть Receiver - получатель
и в команде есть метод execute() который делает receiver.do(params)

2019-06-17 20:36 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
И паттерн проявляет себя, когда есть много отправителей -- например кнопки меню, или клиенты в ресторане заказывают себе что-то, и команда это заказ, получатель -- повар

2019-06-17 20:37 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
а у нас получатель вьюшка или модель, а вот отправитель у нас один -- контроллер

2019-06-17 20:38 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
поэтому у нас нет выхода кроме как вызывать его сразу,
а есть прокидывать команду в получателя -- это странно, так как команда должна дергать получателя, а не наоборот

2019-06-17 20:39 UTC, Hotckiss commented
@ArtyomLobanov фиксед

2019-06-17 20:39 UTC, Hotckiss commented
Ну либо меня что-то смутило и я не поправлял

2019-06-17 20:39 UTC, Hotckiss commented
И что там с сетевым? или его потом?

2019-06-17 20:40 UTC, Hotckiss commented
Выход из игры по нажатию Esc теперь

2019-06-20 03:45 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Паттерн может применяться для разных задач. Например, выполнение действие с объектами, к которым нет прямого доступа. Скажем, если модель у вас хранится на сервере, а контроллер, что логично, на стороне пользователя. Или, менее близкий вариант, если нужно поддерживать историю изменений с возможностью эти изменения откатывать.

2019-06-20 05:36 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
> Паттерн может применяться для разных задач. Например, выполнение действие с объектами, к которым нет прямого доступа. Скажем, если модель у вас хранится на сервере, а контроллер, что логично, на стороне пользователя. Или, менее близкий вариант, если нужно поддерживать историю изменений с возможностью эти изменения откатывать.

Просто мне в этом случае не нравится то, что у нас команда будет по сути просто сигналом(и это получится как будто наблюдатель — сервер получил сигнал, который прокидывается в модель, что-то сама модель делает), с одним прикрепленным char, например. а хочется, чтобы у нее дергался .execute() и данные для обработки у нее были уже

2019-06-20 05:41 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
> Паттерн может применяться для разных задач. Например, выполнение действие с объектами, к которым нет прямого доступа. Скажем, если модель у вас хранится на сервере, а контроллер, что логично, на стороне пользователя. Или, менее близкий вариант, если нужно поддерживать историю изменений с возможностью эти изменения откатывать.

Посмотрел пры других команд, там такая же история, создали и запустили

2019-06-20 05:43 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
> Паттерн может применяться для разных задач. Например, выполнение действие с объектами, к которым нет прямого доступа. Скажем, если модель у вас хранится на сервере, а контроллер, что логично, на стороне пользователя. Или, менее близкий вариант, если нужно поддерживать историю изменений с возможностью эти изменения откатывать.

В примере с сервером — вот я послал команду на сервер, что могло бы храниться в состоянии команды — разве что ввод юзера, так как все на сервере лежит. Ну сейчас так и делается, по сути. Другой вопрос, что мог бы возвращать метод execute() у команды

2019-06-20 05:45 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
> Паттерн может применяться для разных задач. Например, выполнение действие с объектами, к которым нет прямого доступа. Скажем, если модель у вас хранится на сервере, а контроллер, что логично, на стороне пользователя. Или, менее близкий вариант, если нужно поддерживать историю изменений с возможностью эти изменения откатывать.

То есть я еще к тому что execute не должен принимать аргументов, а при создании на коиенте мы бы туда не могли ничего засунуть

2019-06-20 09:43 UTC, ArtyomLobanov requested changes
1. Давайте тогда добавим возможность выкидывать артефакты и ограничим размер инвентаря 5 предметами. А то артефакты, которые у тебя есть, возможно даже надеты, но ты не можешь их снять - странно. 
2. И как потом сервер отключать, если через javaw запускать? Сервер-то с графикой не работает - его и через java можно.
3. _(тут была моя бага т.к. я случайно назвал комнату пустой строкой)_
4. Какой смысл подключаться к игре, которая уже завершена?
5. Не даёт надеть артефакты в сетевой игре
6. Какой смысл возможности сохранения в сетевой игре и как этот сейв потом использовать? Или там неактуальная подсказка показывается?
7. Добавьте информации при выборе сессии. А то непросто догадаться, чего от меня хотят
8. Если адрес/порт указан в неверном формате, было бы мило об этом сообщить, а не просто выкинуть в игрока меню
9. Если указать валидный адрес/порт, но на котором нет сервера, то игра зависает
![image](https://user-images.githubusercontent.com/9067686/59839054-b2f02b00-9358-11e9-824f-5c641da2c37f.png)
10. Добавьте тест на взаимодействие сервера и клиента

2019-06-20 09:43 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/gameloading/GameSaverAndLoader.java
> +                AbstractGameParticipant mob = GenerationUtils.makeMob(c, new Position(x, y));
Метод makeMob мог бы иметь и более точные возвращаемый тип - Mob

2019-06-20 09:43 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/net/server/RoguelikeServer.java
> +                out.writeObject(model);
Давайте в файл карту также сериализовать. Смотрите, как удобно! И не надо по отдельной букве для каждго предмета в игре заводить

2019-06-20 09:43 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
Вам не кажется странным, что класс, с названием ApplyMoveCommand занимается инвентарём?

2019-06-20 09:45 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
Ну, выше было предложение перенести это сюда)

2019-06-20 09:45 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
могу переименовать класс

2019-06-20 09:46 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
Да, давайте переименуем в ApplyTurn или что-нибудь в этом духе

2019-06-20 09:46 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
Хм, дофиксились, в сетевой не поддерживаются цифры потому что...

2019-06-20 09:48 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
И зачем выкидывать артефааты? сейчас модно отключить все, кроме восстанавливающего здоровье, точнее его отключение ничего не даст

2019-06-20 09:49 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
И как появилась уже завершенная игра? Я где-то писал про компромисс, что сессии запрашиваются один раз

2019-06-20 21:53 UTC, Hotckiss commented
@ArtyomLobanov  1 - ok(1-5 включить выключить, 67890 выкинуть 12345 соответственно)
5 6 -- ок
комменты к коду поправил

Так как оставшиеся замечания по сетевой, то предлагаю всем упростить задачу -- закрыть первые три дз, а сетевой уже не исправлять, у всей команды получается оценка 8-9 уже сейчас, а времени осталось совсем мало, лучше остальных допроверять

2019-06-20 22:50 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
> И зачем выкидывать артефааты? сейчас модно отключить все, кроме восстанавливающего здоровье, точнее его отключение ничего не даст

Чтобы освободить место под новые. Если мы оперировать можем только ограниченным числом артефактов, то хочется иметь возможность контролировать их список.

2019-06-20 22:57 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/commands/ApplyMoveCommand.java
> +                    }
> И как появилась уже завершенная игра? Я где-то писал про компромисс, что сессии запрашиваются один раз

Я про то, что в игре уже кто-то нашёл ключик, новые игроки могут подключаться к комнате, но им сразу показывается сообщение "Вы проиграли". Не то, чтобы критично, но довольно странно. Да и список комнат будет разрастаться, если не удалять завершённые.

2019-06-20 23:28 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Команда может принимать контекст. И выполняться она может, например, так `command.execute(model)`. А тогда внутри можно реализовать какую угодно логику, работающую с model, а сама model ничего конкретного про это знать не будет

2019-06-20 23:29 UTC, ArtyomLobanov commented
Бага - при попытке снять несуществующий артефакт вылетает ошибка на сервере
![image](https://user-images.githubusercontent.com/9067686/59886684-a3102f80-93c8-11e9-9e97-be0c9f654888.png)

2019-06-20 23:50 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +            }
Хм. Действительно, везде паттерн определяется строже, чем то, что было у меня в голове. В таком случае логичней всего было бы использовать его в какой-нибудь мапе char->Command для обработки ввода пользователя. Где-нибудь в createCommand вместо switch-case делать запрос к этой мапе.

2019-06-21 07:32 UTC, Hotckiss commented
> Бага - при попытке снять несуществующий артефакт вылетает ошибка на сервере
> ![image](https://user-images.githubusercontent.com/9067686/59886684-a3102f80-93c8-11e9-9e97-be0c9f654888.png)

@ArtyomLobanov ага, потому что 0 это на самом деле 10, и индекс считался неверно, исправил

2019-06-21 17:28 UTC, Hotckiss commented
Ок, вроде как неплохо вышло в итоге, заливаю

2019-06-21 17:28 UTC, merged

2019-06-21 17:31 UTC, ArtyomLobanov commented
Ок.