Hw2 grep
Hotckiss/SoftwareDesign pull request #2
Opened 2019-02-12 15:21 UTC by Hotckiss

2019-03-14 15:13 UTC, ArtyomLobanov requested changes
1. Не надо писать логи в консоль вперемешку с выводом команд. Хотите писать логи - пишите в отдельный файл.
2. Проверяйте корректность переданных значений 
```cmd
>grep -A -10 pattern file
```
3. Решите конфликты с веткой hw1CLI

2019-03-14 15:13 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/GrepCommand.java
> +    private boolean matchesByWord(@NotNull String line,
У ключа -w смысл не в том, чтобы сматчить ровно одно слово, а в том, чтобы не матчить крайние слова кусками.
Должно быть вот так:
```cmd
>echo some text | grep "me text"
some text
>echo some text | grep -w "me text"
*ничего*
>echo so me text | grep -w "me text"
so me text
```
К слову, в регэкспах для границы слова есть специальное обозначение \b.

2019-03-26 22:26 UTC, Hotckiss commented
@ArtyomLobanov ок, поправил
1е замечание досталось по наследству от первого дз еще, поправил при мерже

2019-03-27 19:00 UTC, ArtyomLobanov commented
Какое у вас разнообразие: стек трейс, сообщение на английском и сообщение на русском. Довайте хотя бы от стектрейса избавимся
```cmd
>grep -A -10 compile build.gradle
java.lang.IllegalArgumentException: incorrect parameter value: negetive number of lines
        at kirilenko.cli.commands.implementation.GrepCommand.execute(GrepCommand.java:74)
        at kirilenko.cli.Main.execute(Main.java:54)
        at kirilenko.cli.Main.main(Main.java:33)
>grep -A weds compile build.gradle
"weds" is not a valid value for "-A"
>grep -t compile build.gradle
"-t" недействительная опция
```

2019-03-27 19:05 UTC, Hotckiss commented
> Какое у вас разнообразие: стек трейс, сообщение на английском и сообщение на русском. Довайте хотя бы от стектрейса избавимся
> 
> ```batchfile
> >grep -A -10 compile build.gradle
> java.lang.IllegalArgumentException: incorrect parameter value: negetive number of lines
>         at kirilenko.cli.commands.implementation.GrepCommand.execute(GrepCommand.java:74)
>         at kirilenko.cli.Main.execute(Main.java:54)
>         at kirilenko.cli.Main.main(Main.java:33)
> >grep -A weds compile build.gradle
> "weds" is not a valid value for "-A"
> >grep -t compile build.gradle
> "-t" недействительная опция
> ```

кек, похоже это библиотека пишет на русском что ли, я у себя не нашел такого

2019-03-27 19:11 UTC, Hotckiss commented
@ArtyomLobanov убрал стектрейсы свои так как вообще там все пишется в лог, а остальной вывод в stderr от либы

2019-03-27 19:24 UTC, ArtyomLobanov commented
Теперь вообще ничего не выводится
```cmd
>grep -A -10 compile build.gradle
>echo text
text
```

2019-03-27 19:24 UTC, ArtyomLobanov commented
Пользователь логи не видит - они ему не помогут

2019-03-27 19:25 UTC, Hotckiss commented
@ArtyomLobanov ок, сейчас продублирую erora из лога в stderr

2019-03-27 19:33 UTC, Hotckiss commented
@ArtyomLobanov добавил, должно по идее все шибки выводить, если логгер нигде не забыт (кейсы с грепом проверил что есть)

2019-03-27 19:36 UTC, ArtyomLobanov commented
Ок
@yurii-litvinov

2019-03-27 20:10 UTC, yurii-litvinov requested changes
Судя по диффу, какие-то лишние файлы попали в гит. Почистите, пожалуйста.

2019-03-27 20:10 UTC, yurii-litvinov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/GrepCommand.java
> +        final CmdLineParser parser = new CmdLineParser(this);
Старая Java заставляет писать тип дважды, не пора ли на Java 11 перейти? Не то чтобы прямо сейчас, но на будущее.

2019-03-27 20:10 UTC, yurii-litvinov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/GrepCommand.java
> +            } catch(IOException ex) {
А тут пробела не хватает :)

2019-03-27 20:14 UTC, Hotckiss commented
@yurii-litvinov убрал

2019-03-28 08:52 UTC, yurii-litvinov approved these changes
👍

2019-04-15 13:33 UTC, merged