Hw4
Hotckiss/SoftwareDesign pull request #4
Opened 2019-02-19 21:31 UTC by DmKazakov

2019-02-19 21:39 UTC, Hotckiss approved these changes

2019-03-20 14:51 UTC, ArtyomLobanov commented
О, вы тут без меня разобрались :)
>Hotckiss approved these changes 29 days ago

2019-03-20 15:27 UTC, ArtyomLobanov requested changes
1. Нормализуйте пути
```cmd
>echo src | cd
>echo .. | cd
>pwd
C:\practice\kazakov\SoftwareDesign\hw1CLI\src\..
```
2. Внешние команды не знают про текущую рабочую директорию
```cmd
>echo ../../../.. | cd
>pwd
C:\practice\kazakov\SoftwareDesign\hw1CLI\..\..\..\..
# В текущей директории нет git-репозитория
>git status
On branch hw4
Your branch is up-to-date with 'origin/hw4'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
<..>
```

2019-03-20 15:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/CdCommand.java
> +        if (!input.isEmpty()) {
А если передано 0 аргументов, то ничего не происходит? В bash в таком случае текущая директория меняется на домашнюю.

2019-03-20 15:27 UTC, ArtyomLobanov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/CdCommand.java
> +            throw new CliException("cd: too many arguments");
Через input тут передаётся выход предыдущей команды. Вы пробовали запускать интерпретатор? Вашим cd пользоваться не очень удобно
```
>pwd
C:\practice\kazakov\SoftwareDesign\hw1CLI
>cd src
>pwd
C:\practice\kazakov\SoftwareDesign\hw1CLI
>echo src | cd
>pwd
C:\practice\kazakov\SoftwareDesign\hw1CLI\src
```

2019-03-20 18:19 UTC, DmKazakov commented on hw1CLI/src/main/java/kirilenko/cli/commands/implementation/CdCommand.java
> +        if (!input.isEmpty()) {
@ArtyomLobanov вроде единого мнения о том, что такое домашняя директория в Windows нет, так что я, с вашего позволения, буду считать домашней ту, что выдает `System.getProperty("user.home")`

2019-03-21 14:47 UTC, ArtyomLobanov commented
У ls работу с параметрами тоже нужно поправить
```cmd
>ls 
.gradle .idea build build.gradle CLILog.log CLILog.log.lck gradle gradlew gradlew.bat out settings.gradle src
>ls src
.gradle .idea build build.gradle CLILog.log CLILog.log.lck gradle gradlew gradlew.bat out settings.gradle src
>ls ..
.gradle .idea build build.gradle CLILog.log CLILog.log.lck gradle gradlew gradlew.bat out settings.gradle src
>echo src | ls
main test
```

2019-03-22 18:18 UTC, ArtyomLobanov commented
Ок. 
@yurii-litvinov

2019-03-25 12:13 UTC, yurii-litvinov approved these changes
Всё годно, зачтена

2019-04-15 13:35 UTC, merged