Roguelike 1
Hotckiss/SoftwareDesign pull request #6
Opened 2019-03-09 23:33 UTC by Hotckiss

2019-03-25 17:08 UTC, ArtyomLobanov requested changes
1. Описание предметной области и игровых механик - это хорошо, но добавьте информацию об архитектуре проекта и чем такая архитектура мотивирована.
2. Карта не загружается из файла - падает с
```java
Exception in thread "main" java.lang.NullPointerException
	at ru.roguelike.view.ConsoleViewImpl.lambda$mapRow$1(ConsoleViewImpl.java:173)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at ru.roguelike.view.ConsoleViewImpl.mapRow(ConsoleViewImpl.java:173)
	at ru.roguelike.view.ConsoleViewImpl.lambda$draw$0(ConsoleViewImpl.java:85)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at ru.roguelike.view.ConsoleViewImpl.draw(ConsoleViewImpl.java:85)
	at ru.roguelike.controller.GameController.runGame(GameController.java:47)
	at ru.roguelike.Main.main(Main.java:23)
```
3. Если во время ввода имени файла нажать backspace, то игра тоже перестаёт работать
```java
Exception in thread "main" java.lang.IllegalArgumentException: Cannot create a TextCharacter from a control character (0x8)
	at com.googlecode.lanterna.TextCharacter.<init>(TextCharacter.java:103)
	at com.googlecode.lanterna.TextCharacter.<init>(TextCharacter.java:80)
	at com.googlecode.lanterna.TextCharacter.<init>(TextCharacter.java:52)
	at ru.roguelike.view.ConsoleViewImpl.getFileName(ConsoleViewImpl.java:103)
	at ru.roguelike.view.ConsoleViewImpl.draw(ConsoleViewImpl.java:80)
	at ru.roguelike.controller.GameController.runGame(GameController.java:33)
	at ru.roguelike.Main.main(Main.java:23)
```
4. Что делать, когда нашёл ключ, завершающий игру? Сейчас игра просто перестаёт на всё реагировать, если я правильно понял. Можно было бы новый уровень предложить пройти
5. Нет проверок связности лабиринта. Может так случиться, что ключ достать будет невозможно.
6. Добавьте тесты
7. Добейтесь того, чтобы проект проходил проверку на Travis-е
8. Сделайте так, чтобы jar можно было запускать

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +    public GameController(@NotNull GameModel model, @NotNull ConsoleView view) {
Аннотации `@NotNull` и `@Nullable` - это хорошо, но для них нужно прописывать [зависимость](https://www.jetbrains.com/help/idea/annotating-source-code.html) в gradle.build

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModel.java
> +    void setLoadMapFromFile(boolean loadMapFromFile);
А почему эти методы комментариями обделили?

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +        return (List) fieldModel;
Послушаем, что скажет нам об этом наш приглашённый эксперт
-Какая грязь, какая власть и как приятно в эту грязь упасть
Спасибо, Валерий Александрович.

Вместо этого можно было, например, по-другому объявить метод draw
```java
    <T extends Drawable> DrawingResult draw(List<List<T>> figure, List<String> info, List<String> log,
                       boolean showHelpScreen, boolean loadMapFromFile) throws IOException;
```

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +        KeyStroke keyStroke = screen.readInput();
Таким образом вы привязываете класс ModelImpl к конкретной реализации View - через библиотеку com.googlecode.lanterna. Возможность безболезненно подменять View - одно из приемуществ архитектуры MVC.
Сделайте какую-то промежуточную абстракцию ввода пользователя и возвращайте её,  а не KeyStroke

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +            }
Можно было switch-case сделать

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/Move.java
> +    TOP, LEFT, DOWN, RIGHT, NONE
Мб лучше UP вместо TOP?

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/generators/FromFileGenerator.java
> +        System.out.println(fileName);
Это какой-то дебаговый вывод?

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/generators/FromFileGenerator.java
> +            System.out.println("NOT FILE");
И вот это вот тоже. У вас же логи есть. Пишите туда

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +        return position.getX() >= 0 && position.getY() >= 0 && position.getX() < fieldModel.size() && position.getY() < fieldModel.get(0).size();
Следите за длиной строк, пожалуйста

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +                attack(participant, opponent);
А тут не нужна какая-нибудь проверка, чтобы мобы сами себя не били?

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/generators/FromFileGenerator.java
> +                        field.get(i).add(getMobFromChar(c, new Position(i, j)));
Тут break, наверное, нужен, если вы не хотите одновременно создавать и моба, и артефакт по одной букве

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/generators/FromFileGenerator.java
> +    public static void main(String[] args) throws IOException {
Ух, ты. Ещё один main. Давайте попробуем обойтись одним.

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/Position.java
> +    }
Можно ещё equals/hashCode определить для удобства сравнения позиций. Да и списки списков мапами тогда можно заменить будет при желании

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/artifacts/FinalKey.java
> +public class FinalKey extends AbstractArtifact {
А зачем вам по отдельному классу на каждую сущность, если они отличаются только значениями полей?

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/base/AbstractGameObject.java
> +    // позиция на поле
Согласуйте как-нибудь комментарии - либо везде на русском, либо везде на английском. А то каша какая-то

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/base/AbstractGameParticipant.java
> +        if (random.nextDouble() < freezeProbability) {
Чем каждый раз Random создавать, лучше Math.random() использовать.

2019-03-25 17:08 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/movable/Berserk.java
> +        return new AggressiveStrategy().preferredMove(position, model);
А зачем каждый раз AggressiveStrategy создавать? Почему в поле класса не сохранить?

2019-03-25 17:17 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +    public GameController(@NotNull GameModel model, @NotNull ConsoleView view) {
кажется, п.4-5 не заявлены в требованиях к первой итерации, сейчас если ключ подобран, то пишется что игрок выиграл, и конец, учитывая что сейчас сессия и дедлайн исправлений внезапно в пятницу, то это правильнее делать во 2 итерации

2019-03-25 18:19 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/controller/GameController.java
> +    public GameController(@NotNull GameModel model, @NotNull ConsoleView view) {
> не заявлены в требованиях к первой итерации
> то это правильнее делать во 2 итерации

Ок, справедливо.

>учитывая что сейчас сессия

Да, у меня тоже :(

2019-04-16 18:29 UTC, aliscafo commented
Пункт 2 ("Карта не загружается из файла - падает с NullPointerException") не воспроизводится. Можно ли узнать, на каком примере можно словить такое исключение?

2019-04-16 18:35 UTC, aliscafo commented
Предыдущий комментарий отменяется, исключение получить удалось

2019-05-04 08:35 UTC, ArtyomLobanov requested changes
Когда до конца поправите, позовите через @ArtyomLobanov 
Всё ещё не описана мотивация использования именно такой архитектуры
Про диаграмму:
1. Поля у интерфейса? 
![image](https://user-images.githubusercontent.com/9067686/57068273-ea881280-6cd9-11e9-9368-b2b960b9a00f.png)
И почему метод clear тут не указан, а в ViewImpl указан?
2. StrategyUtils - это не класс в полном смысле этого слова. 
3. Плохо, что знания об используемой для отрисовки библиотеке уходят за границы ViewImpl через использование Screen в ConsoleView и KeyStroke в Movable

2019-05-04 08:35 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/models/objects/base/AbstractGameParticipant.java
> +    protected int fullHealth;
protected модификатор в java работает довольно криво - влечёт за собой ещё и пакетную видимость. Да и вообще прямая манипуляция полями извне, даже наследниками класса, может привести к непредвиденным проблемам с какими-нибудь внутренними инвариантами. Лучше работать через get/set. А в вашем случае они в потомках вообще никак не используются, кроме инициализации в конструкторе. В таком случае лучше создать в AbstractGameParticipant конструктор, принимающий значения полей, и передавать начальные значения в потомках через этот конструктор.

2019-06-01 21:22 UTC, Hotckiss commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +                attack(participant, opponent);
а там внутри метода проверяется, что ровно один из них player, другой нет

2019-06-02 07:59 UTC, ArtyomLobanov reviewed
Перенесите, пожалуйста, исправления в актуальную ветку. Для удобства, в дальнейшем проверять и исправлять будем только её.
От документации всё ещё хочется больше **слов** про архитектуру. Что, зачем, почему...
И тесты ещё нужны

2019-06-02 07:59 UTC, ArtyomLobanov commented on roguelike/build.gradle
> +
Не указана точка входа в программу -- jar нельзя запустить
```cmd
C:\practice\games\kirilenko-lupulyak-erohina\SoftwareDesign\roguelike>java -jar build\libs\roguelike-1.0-SNAPSHOT.jar
no main manifest attribute, in build\libs\roguelike-1.0-SNAPSHOT.jar
```

2019-06-02 07:59 UTC, ArtyomLobanov commented on roguelike/src/main/java/ru/roguelike/logic/GameModelImpl.java
> +        }
Чем явно проверять принадлежность к классам, лучше было бы сделать отличающуюся логику частью интерфейса. Например, ввести метод `String getName()` в AbstractGameParticipant и в лог писать 
```java
gameLog.add(attacker.getName() + " attacks " + defender.getName());
```

2019-06-02 08:01 UTC, Hotckiss commented on roguelike/build.gradle
> +
Ага, я вчера ночью уже заснул, сегодня планировал все дофиксить и перетащить в третью ветку

2019-06-02 08:04 UTC, ArtyomLobanov commented on roguelike/build.gradle
> +
Когда будете чинить, откройте ещё, пожалуйста, пул-реквест из актуальной ветки в пустую

2019-06-02 08:06 UTC, Hotckiss commented on roguelike/build.gradle
> +
ок, я сделаю просто из третьей в мастер и будем сразу все три дз закрывать

2019-06-02 18:44 UTC, Hotckiss commented
Так, остались тесты
И мотивация архитектуры в ридми, но ее пишу не я

2019-06-20 21:54 UTC, closed without merging